version: 2
jobs:
  build:
    working_directory: ~/ngo
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: ngo-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: ngo-simple-app-{{ .Branch }}-{{ checksum "integration/webpack/simple-app/yarn.lock" }}
      - restore_cache:
          key: ngo-aio-app-{{ .Branch }}-{{ checksum "integration/webpack/aio-app/yarn.lock" }}
      - run: yarn
      - run: yarn lint
      - run: yarn test
      # - run: xvfb-run -a yarn integration
      - run:
          # add `export DISPLAY=:99.0` to commands that use this display.
          name: Running X virtual framebuffer
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - run: |
          export DISPLAY=:99.0
          yarn integration
      - run: yarn benchmark
      - save_cache:
          key: ngo-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - save_cache:
          key: ngo-simple-app-{{ .Branch }}-{{ checksum "integration/webpack/simple-app/yarn.lock" }}
          paths:
            - "integration/webpack/simple-app/node_modules"
      - save_cache:
          key: ngo-aio-app-{{ .Branch }}-{{ checksum "integration/webpack/aio-app/yarn.lock" }}
          paths:
            - "integration/webpack/aio-app/node_modules"
